# Python image
FROM python:3.10.15-alpine3.20

RUN apk update && apk add --no-cache \
    gcc \
    musl-dev \
    libffi-dev \
    openblas-dev \
    g++ \
    && apk add --no-cache --virtual .build-deps \
    build-base \
    linux-headers

WORKDIR /app

COPY requirements.txt .

RUN pip show pip

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "app.py"]
